# Generated by Django 5.0.1 on 2024-02-17 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("total_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Convenience",
            fields=[
                ("convenienceId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="Default Convenience Name", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("custom_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, default="profile1.png", null=True, upload_to=""
                    ),
                ),
                ("phonenumber", models.CharField(max_length=15)),
                (
                    "membership",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("normal", "Normal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("hotel_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("five-star", "five-star"),
                            ("three-star", "three-star"),
                            ("one-star", "one-star"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=30)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("conveniences", models.ManyToManyField(to="myApp.convenience")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=10)),
                ("comment", models.TextField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.hotel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "roomtype",
                    models.CharField(
                        choices=[
                            ("single", "單人房"),
                            ("double", "標準雙人房"),
                            ("suite", "豪華三人套房"),
                        ],
                        max_length=6,
                    ),
                ),
                ("price", models.IntegerField()),
                ("availability", models.BooleanField(default=True)),
                ("capacity", models.IntegerField(default=1)),
                ("conveniences", models.ManyToManyField(to="myApp.convenience")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.hotel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Hotels",
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.customer"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.hotel"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.room"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.booking"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myApp.customer"
            ),
        ),
    ]
