# Generated by Django 5.0.1 on 2024-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_booking_convenience_customer_hotel_review_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="roomImages/"),
        ),
    ]
