# Generated by Django 5.0.1 on 2024-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_number",
            field=models.CharField(default=666, max_length=10),
        ),
    ]
