# Generated by Django 5.0.1 on 2024-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_room_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.IntegerField(default=5),
        ),
    ]
