# Generated by Django 5.0.1 on 2024-02-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_room_floor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_number",
            new_name="roomNumber",
        ),
    ]
