# Generated by Django 5.0.1 on 2024-02-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_rename_room_number_room_roomnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="totalRooms",
            field=models.IntegerField(default=5),
        ),
    ]
