# Generated by Django 5.0.1 on 2024-02-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_room_totalrooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="availability",
        ),
    ]
