# Generated by Django 5.0.1 on 2024-02-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_remove_room_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hotelimages/"),
        ),
    ]
